### ISSUE TITLE
SVG is successfully loaded but not rendered in the DOM

### ISSUE THREAD

**Issue by arquadrado** [arkon/ng-inline-svg#119]
I have exactly the same problem described above. I have to svg being loaded sucessfully in the network tab but then it is not added to the dom.

This is my component:
```
<div
  class="icon"
  [ngStyle]="{ width: width, height: height }"
  [inlineSVG]="imagePath"
  [setSVGAttributes]="{ style: 'position: absolute; top: 0; left: 0;' }"
></div>
```

and in the dom I just have the empty div

`<div _ngcontent-gmp-c5="" class="icon" ng-reflect-ng-style="[object Object]" ng-reflect-inline-s-v-g="assets/img/svg/menu.svg" ng-reflect-set-s-v-g-attributes="[object Object]" style="width: 32px; height: 32px;"></div>`

Did anyone managed to figure out what is happening here?

_Originally posted by @arquadrado in https://github.com/arkon/ng-inline-svg/issues/66#issuecomment-528387485_

**Comment by keito99** [comment]
**My Case:**
If the svg path is located in the same domain, it works.
Buy if the svg is located in other domain, e.g. (CDN), it didn't works.

**Reason:**
Although the svg is successfully loaded. It is blocked by browser due to "Cross-Origin Request Blocked" (CORS) security reason.

**My Solution:**
If you can modify the server side storing the svg file, add header "Access-Control-Allow-Origin", "*".

BEFORE:
app.use(express.static(__dirname + '/../public'));

AFTER:
app.use(express.static(__dirname + '/../public', {
            setHeaders: function(res, path) {
                res.set("Access-Control-Allow-Origin", "*");
            }
        }
    ));

**Comment by iplus26** [comment]
In my case, my HttpInterceptor incorrectly handled the svg request, so svg was "not rendered" (not inserted to dom) but `ng-inline-svg` doesn't throw an error (may be something to enhance).

I will suggest you set debuggers at "insert method" of `ng-inline-svg`, and see what's going wrong

**Comment by iplus26** [comment]
Check whether this line is executed: [svg-cache.service.ts#L167](https://github.com/arkon/ng-inline-svg/blob/7d23a6ce3c93e7b13156cc727f5ea055f5a34acd/src/svg-cache.service.ts#L67)
