### ISSUE TITLE
Make svg styles private/local?

### ISSUE THREAD

**Issue by liuxh0** [arkon/ng-inline-svg#40]
Hi Arkon,

I am currently using your component, it's great! But I am facing a problem: In my svgs are styles embedded, something like this
```
<svg ..>
  <style type="text/css">
  <![CDATA[
    .st0{ fill:#000; }
  ]]>
  </style>
  ...
</svg>
```
If I'm inlining the svg, the styles are also "imported". This is not what I want, because it pollutes my global css. If I have another svg using class "st0", the style could be wrong.

Maybe I'm using svg in a wrong way? Otherwise I'm thinking, maybe we could make the classes inside svg "private" by renaming classes to make them unique.

**Comment by arkon** [comment]
I don't like the idea of automatically modifying the class names or styles since that seems like pretty unpredictable behaviour. The current (buggy?) behaviour is expected, since that's exactly what should happen if you were to have multiple SVGs inlined with overlapping styles.

You can always modifying your SVGs' styles, or use inline styles (assuming you're using something like Illustrator to generate them) instead.
