### ISSUE TITLE
onSVGLoaded

### ISSUE THREAD

**Issue by zygimantas** [arkon/ng-inline-svg#70]
Based on this example https://github.com/arkon/ng-inline-svg/blob/3eae11e3b276d819c7326af3e0c1b4b8b5b647a9/demo/src/demo/demo.component.ts is it possible to call another public/private method of component from inside the handleSVG method?

I am getting:

```
core.js:1374 ERROR TypeError: this.setBaseColor is not a function
    at InlineSVGDirective.onSVGLoaded (common-pirate.component.ts:37)
    at SafeSubscriber.eval [as _next] (inline-svg.directive.js:80)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:231)
    at SafeSubscriber.next (Subscriber.js:179)
    at Subscriber._next (Subscriber.js:122)
    at Subscriber.next (Subscriber.js:86)
    at MapSubscriber._next (map.js:75)
    at MapSubscriber.next (Subscriber.js:86)
    at RefCountSubscriber._next (Subscriber.js:122)
    at RefCountSubscriber.next (Subscriber.js:86)
```

And why this new functionality is defined differently than existing "onSVGInserted"?

[onSVGLoaded]="onSVGLoaded"
(onSVGInserted)="onSVGInserted($event)"?

"this" is InlineSVGDirective inside handleSVG(svgElement: SVGElement), so how to reference the component?

**Comment by gethinoakes** [comment]
Just want to add that for `[onSVGLoaded]` I get the following error from Angular:

> Binding to event property 'onSVGLoaded' is disallowed for security reasons, please use (SVGLoaded)=...
> If 'onSVGLoaded' is a directive input, make sure the directive is imported by the current module.

**Comment by zygimantas** [comment]
gethinoakes remove node_modules and reinstall. It helped me to solve this particular issue you have.

**Comment by gethinoakes** [comment]
Thanks @zygimantas that worked!

**Comment by gethinoakes** [comment]
I'm also having issues with `onSVGLoaded`, so will comment here (apologies if you'd prefer a separate issue).

I want to prefix the class names in the SVG generated by adobe xd, which I can do by using regex,
```
handleSVG(svg: SVGElement): any {
    console.log('Loaded SVG', svg);
    svg.children[0].children[0].textContent.replace(/(cls)/g, 'groups-cls');
    return svg;
  }
```

However this doesn't actually work, the SVG is returned as normal with no manipulation. If I stick a debugger in there before `return svg` then I can see that the regex worked.

Also I'm wondering if there would be a way to access the parent element of the SVG (doesn't work with this property) to access that class to use as the prefix when replacing the classes in the SVG. Otherwise I would have to potentially have a different function for each icon. Unless we can have some sort of `class` input that applies a class directly to the SVG and then that could be used.

**Comment by arkon** [comment]
> is it possible to call another public/private method of component from inside the handleSVG method?

You should be able to bind the function's context first. Something along the lines of:

```html
<div [onSVGInserted]="myFunc" ...></div>
```

```ts
class MyComponent {
  private myFunc = this.handler.bind(this);

  handler(svg: SVGElement): SVGElement {
    return svg;
  }
}
```

I haven't actually tested that though -- let me know if it works.

> And why this new functionality is defined differently than existing "onSVGInserted"?

Because I need the return value of the function, whereas the other one is a fire and forget event from the directive's perspective.

> However this doesn't actually work, the SVG is returned as normal with no manipulation.

I'll need to look into that later.

> Also I'm wondering if there would be a way to access the parent element of the SVG

You mean from your Angular template?

**Comment by gethinoakes** [comment]
> You mean from your Angular template?

Yes, so currently I have this:
```
<button class="icon-btn groups" [inlineSVG]="'/assets/icons/header/groups.svg' [onSVGLoaded]="handleSVG" forceEvalStyles="true"></button>
```

But multiple of these, so ideally there would be some way of accessing the button element with `onSVGLoaded` so I could take its class and prefix the SVG classes with it, as shown which is what I'm trying to do in my previous post.

However I can't access it with `svg.parentElement`, I assume this is because of the lifecycle?

The PR I just opened would allow us to add a class directly to the SVG though, which would mitigate this as I could then use that class to prefix the rest of the classes inside the SVG.

**Comment by arkon** [comment]
I could probably pass a reference to the element to the lifecycle handler.

**Comment by arkon** [comment]
Added a reference to the parent element as the second argument to `onSVGLoaded` in v6.2.1.

**Comment by gethinoakes** [comment]
Thanks, that's great. And I see in your demo code that `svg.setAttribute('width', '100');` works to manipulate the SVG, however I still can't get the classes to add their prefix... any idea where I'm going wrong with this?

`svg.children[0].children[0].textContent.replace(/(cls)/g, 'groups-cls');`

I know this is out of scope for this library, but any help would be appreciated :)

**Edit:**
Got it working with
`svg.children[0].children[0].textContent = svg.children[0].children[0].textContent.replace(/(cls)/g, 'groups-cls');`

Thanks!

**Comment by cyphercodes96** [comment]
[onSVGLoaded] lifecycle hook never worked with me...

I couldn't even console.log('testing')';
I'm testing on both of the following:
**test 1 with button as you did above**
  <button class="icon-btn groups" [inlineSVG]="'/assets/Teeth/16_layers.svg'" (onSVGLoaded)="handleSVG"></button>

**test 2 with div, exactly how i want it, or with <th> tags**
 < < div id="svg1"
          [inlineSVG]="'/assets/Teeth/16_layers.svg'"
          (click)="svgClicked()"
          [onSVGLoaded]="handleSVG">   < / div>
--> which results in a security problem and asks me to use (SVGLoaded) = " " which i also tested and never worked as i thought it would
This is my handleSVG function
  handleSVG(svg: SVGElement): any {
    console.log(svg);
    console.log('testing');
    return svg;
  }

Tried deleting Node_Modules and reinstalling and to no avail.

Help me on this if possible

**Comment by arkon** [comment]
@cyphercodes96 Please don't post in other places to try to get someone to answer. It's literally only been 4 hours.

Make sure you have the right version installed (^6.2.0). It's an input so it has to be `[onSVGLoaded]`.

**Comment by cyphercodes96** [comment]
@arkon Oh but did I post in any other places? if so i'm sorry, i received an email where you closed #70, so i replied back to you through that email thinking you should receive it or something :/ Yea i'm on version 6.0.0, upgrading now and i'll test it and keep you posted!

**Comment by cyphercodes96** [comment]
@arkon works like a charm!
Perfect!

Thank you for your help

**Comment by cyphercodes96** [comment]
@arkon Having another issue with onSVGLoaded.

The function handleSVG() is being triggered, but inside it, none of my component variables / functions are defined. although in the console log, i get a the value i want defined before the handleSVG get's triggered, but inside the handleSVG, the value / variable is undefined

Same with the onSVGInserted, so whatever logic i'm doing inside the handleSVG(), it's telling me that I have undefined values ( variable's are not yet initialized )

  handleSVG(svg: SVGElement): any {
    const x = setInterval(() => {
      console.log('inside interval');
      console.log(this.loaded);
      if (this.loaded) {
        this.svgArray.push(svg);
        console.log(this.svgArray);
        clearInterval(x);
      }
    }, 1000);
    return svg;
  }

Idea's?

**Comment by cyphercodes96** [comment]
Update from my end:

I was capable of achieving what i want ( pushing all svg files to an array so that i can handle them and manipulate them later in that component depending on future conditions to be fetched inside that component ) as follows:
<th
[inlineSVG]="'/assets/Teeth/Tooth' + tooth.position + '.svg'"
[onSVGLoaded]="myFunc">
</th>
  myFunc = this.handleSVG.bind(this);

  handleSVG(svg: SVGElement): any {
    this.saveSVG(svg);
    return svg;
  }

  saveSVG(svg: SVGElement) {
    if (this.loaded) {
      this.svgArray.push(svg);
      console.log(this.svgArray);
    }
  }

**Comment by arkon** [comment]
Yes, as previously mentioned you just need to bind the function's context first.
